'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


Partial Public Class LivePersonDataDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  #End Region
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property Sessions() As System.Data.Linq.Table(Of Session)
		Get
			Return Me.GetTable(Of Session)
		End Get
	End Property
	
	Public ReadOnly Property GeneralChatInfos() As System.Data.Linq.Table(Of GeneralChatInfo)
		Get
			Return Me.GetTable(Of GeneralChatInfo)
		End Get
	End Property
	
	Public ReadOnly Property ChatTranscripts() As System.Data.Linq.Table(Of ChatTranscript)
		Get
			Return Me.GetTable(Of ChatTranscript)
		End Get
	End Property
	
	Public ReadOnly Property Navigations() As System.Data.Linq.Table(Of Navigation)
		Get
			Return Me.GetTable(Of Navigation)
		End Get
	End Property
	
	Public ReadOnly Property PreChatSurveys() As System.Data.Linq.Table(Of PreChatSurvey)
		Get
			Return Me.GetTable(Of PreChatSurvey)
		End Get
	End Property
	
	Public ReadOnly Property CustomVariables() As System.Data.Linq.Table(Of CustomVariables)
		Get
			Return Me.GetTable(Of CustomVariables)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="")>  _
Partial Public Class Session
	
	Private _Start As String
	
	Private _Duration As String
	
	Private _Operator As String
	
	Private _RealTimeSessionID As String
	
	Private _message As String
	
	Private _Extension As String
	
	Private _Ticket As String
	
	Private _skill As String
	
	Private _phoneNumber As String
	
	Private _email As String
	
	Private _subject As String
	
	Private _Country As String
	
	Private _identifier As String
	
	Private _Survey_PreChat As String
	
	Private _Survey_Exit As String
	
	Private _Survey_Operator As String
	
	Private _Survey_Offline As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Start", CanBeNull:=false)>  _
	Public Property Start() As String
		Get
			Return Me._Start
		End Get
		Set
			If (String.Equals(Me._Start, value) = false) Then
				Me._Start = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Duration", CanBeNull:=false)>  _
	Public Property Duration() As String
		Get
			Return Me._Duration
		End Get
		Set
			If (String.Equals(Me._Duration, value) = false) Then
				Me._Duration = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="Operator", Storage:="_Operator", CanBeNull:=false)>  _
	Public Property [Operator]() As String
		Get
			Return Me._Operator
		End Get
		Set
			If (String.Equals(Me._Operator, value) = false) Then
				Me._Operator = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RealTimeSessionID", CanBeNull:=false)>  _
	Public Property RealTimeSessionID() As String
		Get
			Return Me._RealTimeSessionID
		End Get
		Set
			If (String.Equals(Me._RealTimeSessionID, value) = false) Then
				Me._RealTimeSessionID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_message", CanBeNull:=false)>  _
	Public Property message() As String
		Get
			Return Me._message
		End Get
		Set
			If (String.Equals(Me._message, value) = false) Then
				Me._message = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Extension", CanBeNull:=false)>  _
	Public Property Extension() As String
		Get
			Return Me._Extension
		End Get
		Set
			If (String.Equals(Me._Extension, value) = false) Then
				Me._Extension = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Ticket", CanBeNull:=false)>  _
	Public Property Ticket() As String
		Get
			Return Me._Ticket
		End Get
		Set
			If (String.Equals(Me._Ticket, value) = false) Then
				Me._Ticket = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_skill", CanBeNull:=false)>  _
	Public Property skill() As String
		Get
			Return Me._skill
		End Get
		Set
			If (String.Equals(Me._skill, value) = false) Then
				Me._skill = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_phoneNumber", CanBeNull:=false)>  _
	Public Property phoneNumber() As String
		Get
			Return Me._phoneNumber
		End Get
		Set
			If (String.Equals(Me._phoneNumber, value) = false) Then
				Me._phoneNumber = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_email", CanBeNull:=false)>  _
	Public Property email() As String
		Get
			Return Me._email
		End Get
		Set
			If (String.Equals(Me._email, value) = false) Then
				Me._email = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_subject", CanBeNull:=false)>  _
	Public Property subject() As String
		Get
			Return Me._subject
		End Get
		Set
			If (String.Equals(Me._subject, value) = false) Then
				Me._subject = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Country", CanBeNull:=false)>  _
	Public Property Country() As String
		Get
			Return Me._Country
		End Get
		Set
			If (String.Equals(Me._Country, value) = false) Then
				Me._Country = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_identifier", CanBeNull:=false)>  _
	Public Property identifier() As String
		Get
			Return Me._identifier
		End Get
		Set
			If (String.Equals(Me._identifier, value) = false) Then
				Me._identifier = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Survey_PreChat", CanBeNull:=false)>  _
	Public Property Survey_PreChat() As String
		Get
			Return Me._Survey_PreChat
		End Get
		Set
			If (String.Equals(Me._Survey_PreChat, value) = false) Then
				Me._Survey_PreChat = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Survey_Exit", CanBeNull:=false)>  _
	Public Property Survey_Exit() As String
		Get
			Return Me._Survey_Exit
		End Get
		Set
			If (String.Equals(Me._Survey_Exit, value) = false) Then
				Me._Survey_Exit = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Survey_Operator", CanBeNull:=false)>  _
	Public Property Survey_Operator() As String
		Get
			Return Me._Survey_Operator
		End Get
		Set
			If (String.Equals(Me._Survey_Operator, value) = false) Then
				Me._Survey_Operator = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Survey_Offline", CanBeNull:=false)>  _
	Public Property Survey_Offline() As String
		Get
			Return Me._Survey_Offline
		End Get
		Set
			If (String.Equals(Me._Survey_Offline, value) = false) Then
				Me._Survey_Offline = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="")>  _
Partial Public Class GeneralChatInfo
	
	Private _StartTime As String
	
	Private _EndTime As String
	
	Private _Duration As String
	
	Private _StartingPage As String
	
	Private _Operator As String
	
	Private _Browser As String
	
	Private _OS As String
	
	Private _IP As String
	
	Private _Referrer As String
	
	Private _ChatIndicator As String
	
	Private _RealTimeSessionID As String
	
	Private _Country As String
	
	Private _City As String
	
	Private _Org As String
	
	Private _Region As String
	
	Private _Timezone As String
	
	Private _ISP As String
	
	Private _WorldRegion As String
	
	Private _HostAddr As String
	
	Private _PostalCode As String
	
	Private _ConnectionType As String
	
	Private _Country1 As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartTime", CanBeNull:=false)>  _
	Public Property StartTime() As String
		Get
			Return Me._StartTime
		End Get
		Set
			If (String.Equals(Me._StartTime, value) = false) Then
				Me._StartTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EndTime", CanBeNull:=false)>  _
	Public Property EndTime() As String
		Get
			Return Me._EndTime
		End Get
		Set
			If (String.Equals(Me._EndTime, value) = false) Then
				Me._EndTime = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Duration", CanBeNull:=false)>  _
	Public Property Duration() As String
		Get
			Return Me._Duration
		End Get
		Set
			If (String.Equals(Me._Duration, value) = false) Then
				Me._Duration = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_StartingPage", CanBeNull:=false)>  _
	Public Property StartingPage() As String
		Get
			Return Me._StartingPage
		End Get
		Set
			If (String.Equals(Me._StartingPage, value) = false) Then
				Me._StartingPage = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="Operator", Storage:="_Operator", CanBeNull:=false)>  _
	Public Property [Operator]() As String
		Get
			Return Me._Operator
		End Get
		Set
			If (String.Equals(Me._Operator, value) = false) Then
				Me._Operator = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Browser", CanBeNull:=false)>  _
	Public Property Browser() As String
		Get
			Return Me._Browser
		End Get
		Set
			If (String.Equals(Me._Browser, value) = false) Then
				Me._Browser = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_OS", CanBeNull:=false)>  _
	Public Property OS() As String
		Get
			Return Me._OS
		End Get
		Set
			If (String.Equals(Me._OS, value) = false) Then
				Me._OS = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IP", CanBeNull:=false)>  _
	Public Property IP() As String
		Get
			Return Me._IP
		End Get
		Set
			If (String.Equals(Me._IP, value) = false) Then
				Me._IP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Referrer", CanBeNull:=false)>  _
	Public Property Referrer() As String
		Get
			Return Me._Referrer
		End Get
		Set
			If (String.Equals(Me._Referrer, value) = false) Then
				Me._Referrer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ChatIndicator", CanBeNull:=false)>  _
	Public Property ChatIndicator() As String
		Get
			Return Me._ChatIndicator
		End Get
		Set
			If (String.Equals(Me._ChatIndicator, value) = false) Then
				Me._ChatIndicator = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RealTimeSessionID", CanBeNull:=false)>  _
	Public Property RealTimeSessionID() As String
		Get
			Return Me._RealTimeSessionID
		End Get
		Set
			If (String.Equals(Me._RealTimeSessionID, value) = false) Then
				Me._RealTimeSessionID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Country", CanBeNull:=false)>  _
	Public Property Country() As String
		Get
			Return Me._Country
		End Get
		Set
			If (String.Equals(Me._Country, value) = false) Then
				Me._Country = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_City", CanBeNull:=false)>  _
	Public Property City() As String
		Get
			Return Me._City
		End Get
		Set
			If (String.Equals(Me._City, value) = false) Then
				Me._City = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Org", CanBeNull:=false)>  _
	Public Property Org() As String
		Get
			Return Me._Org
		End Get
		Set
			If (String.Equals(Me._Org, value) = false) Then
				Me._Org = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Region", CanBeNull:=false)>  _
	Public Property Region() As String
		Get
			Return Me._Region
		End Get
		Set
			If (String.Equals(Me._Region, value) = false) Then
				Me._Region = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Timezone", CanBeNull:=false)>  _
	Public Property Timezone() As String
		Get
			Return Me._Timezone
		End Get
		Set
			If (String.Equals(Me._Timezone, value) = false) Then
				Me._Timezone = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ISP", CanBeNull:=false)>  _
	Public Property ISP() As String
		Get
			Return Me._ISP
		End Get
		Set
			If (String.Equals(Me._ISP, value) = false) Then
				Me._ISP = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WorldRegion", CanBeNull:=false)>  _
	Public Property WorldRegion() As String
		Get
			Return Me._WorldRegion
		End Get
		Set
			If (String.Equals(Me._WorldRegion, value) = false) Then
				Me._WorldRegion = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_HostAddr", CanBeNull:=false)>  _
	Public Property HostAddr() As String
		Get
			Return Me._HostAddr
		End Get
		Set
			If (String.Equals(Me._HostAddr, value) = false) Then
				Me._HostAddr = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PostalCode", CanBeNull:=false)>  _
	Public Property PostalCode() As String
		Get
			Return Me._PostalCode
		End Get
		Set
			If (String.Equals(Me._PostalCode, value) = false) Then
				Me._PostalCode = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ConnectionType", CanBeNull:=false)>  _
	Public Property ConnectionType() As String
		Get
			Return Me._ConnectionType
		End Get
		Set
			If (String.Equals(Me._ConnectionType, value) = false) Then
				Me._ConnectionType = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Country1", CanBeNull:=false)>  _
	Public Property Country1() As String
		Get
			Return Me._Country1
		End Get
		Set
			If (String.Equals(Me._Country1, value) = false) Then
				Me._Country1 = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="")>  _
Partial Public Class ChatTranscript
	
	Private _Timestamp As String
	
	Private _Name As String
	
	Private _Text As String
	
	Private _RealTimeSessionID As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Timestamp", CanBeNull:=false)>  _
	Public Property Timestamp() As String
		Get
			Return Me._Timestamp
		End Get
		Set
			If (String.Equals(Me._Timestamp, value) = false) Then
				Me._Timestamp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Name", CanBeNull:=false)>  _
	Public Property Name() As String
		Get
			Return Me._Name
		End Get
		Set
			If (String.Equals(Me._Name, value) = false) Then
				Me._Name = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Text", CanBeNull:=false)>  _
	Public Property Text() As String
		Get
			Return Me._Text
		End Get
		Set
			If (String.Equals(Me._Text, value) = false) Then
				Me._Text = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RealTimeSessionID", CanBeNull:=false)>  _
	Public Property RealTimeSessionID() As String
		Get
			Return Me._RealTimeSessionID
		End Get
		Set
			If (String.Equals(Me._RealTimeSessionID, value) = false) Then
				Me._RealTimeSessionID = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="")>  _
Partial Public Class Navigation
	
	Private _SeqNo As String
	
	Private _URL As String
	
	Private _Timestamp As String
	
	Private _RealTimeSessionID As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_SeqNo", CanBeNull:=false)>  _
	Public Property SeqNo() As String
		Get
			Return Me._SeqNo
		End Get
		Set
			If (String.Equals(Me._SeqNo, value) = false) Then
				Me._SeqNo = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_URL", CanBeNull:=false)>  _
	Public Property URL() As String
		Get
			Return Me._URL
		End Get
		Set
			If (String.Equals(Me._URL, value) = false) Then
				Me._URL = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Timestamp", CanBeNull:=false)>  _
	Public Property Timestamp() As String
		Get
			Return Me._Timestamp
		End Get
		Set
			If (String.Equals(Me._Timestamp, value) = false) Then
				Me._Timestamp = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RealTimeSessionID", CanBeNull:=false)>  _
	Public Property RealTimeSessionID() As String
		Get
			Return Me._RealTimeSessionID
		End Get
		Set
			If (String.Equals(Me._RealTimeSessionID, value) = false) Then
				Me._RealTimeSessionID = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="")>  _
Partial Public Class PreChatSurvey
	
	Private _IdentifierName As String
	
	Private _Email As String
	
	Private _Phone As String
	
	Private _CompanyName As String
	
	Private _From As String
	
	Private _RealTimeSessionID As String
	
	Private _Country As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IdentifierName", CanBeNull:=false)>  _
	Public Property IdentifierName() As String
		Get
			Return Me._IdentifierName
		End Get
		Set
			If (String.Equals(Me._IdentifierName, value) = false) Then
				Me._IdentifierName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Email", CanBeNull:=false)>  _
	Public Property Email() As String
		Get
			Return Me._Email
		End Get
		Set
			If (String.Equals(Me._Email, value) = false) Then
				Me._Email = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Phone", CanBeNull:=false)>  _
	Public Property Phone() As String
		Get
			Return Me._Phone
		End Get
		Set
			If (String.Equals(Me._Phone, value) = false) Then
				Me._Phone = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CompanyName", CanBeNull:=false)>  _
	Public Property CompanyName() As String
		Get
			Return Me._CompanyName
		End Get
		Set
			If (String.Equals(Me._CompanyName, value) = false) Then
				Me._CompanyName = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Name:="From", Storage:="_From", CanBeNull:=false)>  _
	Public Property [From]() As String
		Get
			Return Me._From
		End Get
		Set
			If (String.Equals(Me._From, value) = false) Then
				Me._From = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RealTimeSessionID", CanBeNull:=false)>  _
	Public Property RealTimeSessionID() As String
		Get
			Return Me._RealTimeSessionID
		End Get
		Set
			If (String.Equals(Me._RealTimeSessionID, value) = false) Then
				Me._RealTimeSessionID = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Country", CanBeNull:=false)>  _
	Public Property Country() As String
		Get
			Return Me._Country
		End Get
		Set
			If (String.Equals(Me._Country, value) = false) Then
				Me._Country = value
			End If
		End Set
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="")>  _
Partial Public Class CustomVariables
	
	Private _Skill As String
	
	Private _Abandon As String
	
	Private _VisitorActive As String
	
	Private _lpTagVer As String
	
	Private _campaign_medium As String
	
	Private _campaign_source As String
	
	Private _RealTimeSessionID As String
	
	Public Sub New()
		MyBase.New
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Skill", CanBeNull:=false)>  _
	Public Property Skill() As String
		Get
			Return Me._Skill
		End Get
		Set
			If (String.Equals(Me._Skill, value) = false) Then
				Me._Skill = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_Abandon", CanBeNull:=false)>  _
	Public Property Abandon() As String
		Get
			Return Me._Abandon
		End Get
		Set
			If (String.Equals(Me._Abandon, value) = false) Then
				Me._Abandon = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_VisitorActive", CanBeNull:=false)>  _
	Public Property VisitorActive() As String
		Get
			Return Me._VisitorActive
		End Get
		Set
			If (String.Equals(Me._VisitorActive, value) = false) Then
				Me._VisitorActive = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_lpTagVer", CanBeNull:=false)>  _
	Public Property lpTagVer() As String
		Get
			Return Me._lpTagVer
		End Get
		Set
			If (String.Equals(Me._lpTagVer, value) = false) Then
				Me._lpTagVer = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_campaign_medium", CanBeNull:=false)>  _
	Public Property campaign_medium() As String
		Get
			Return Me._campaign_medium
		End Get
		Set
			If (String.Equals(Me._campaign_medium, value) = false) Then
				Me._campaign_medium = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_campaign_source", CanBeNull:=false)>  _
	Public Property campaign_source() As String
		Get
			Return Me._campaign_source
		End Get
		Set
			If (String.Equals(Me._campaign_source, value) = false) Then
				Me._campaign_source = value
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_RealTimeSessionID", CanBeNull:=false)>  _
	Public Property RealTimeSessionID() As String
		Get
			Return Me._RealTimeSessionID
		End Get
		Set
			If (String.Equals(Me._RealTimeSessionID, value) = false) Then
				Me._RealTimeSessionID = value
			End If
		End Set
	End Property
End Class
