<?xml version="1.0" encoding="utf-8"?><Database Class="LivePersonDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="Sessions">
    <Type Name="Session">
      <Column Name="Start" Type="System.String" CanBeNull="false" />
      <Column Name="Duration" Type="System.String" CanBeNull="false" />
      <Column Name="Operator" Type="System.String" CanBeNull="false" />
      <Column Name="RealTimeSessionID" Type="System.String" CanBeNull="false" />
      <Column Name="message" Type="System.String" CanBeNull="false" />
      <Column Name="Extension" Type="System.String" CanBeNull="false" />
      <Column Name="Ticket" Type="System.String" CanBeNull="false" />
      <Column Name="skill" Type="System.String" CanBeNull="false" />
      <Column Name="phoneNumber" Type="System.String" CanBeNull="false" />
      <Column Name="email" Type="System.String" CanBeNull="false" />
      <Column Name="subject" Type="System.String" CanBeNull="false" />
      <Column Name="Country" Type="System.String" CanBeNull="false" />
      <Column Name="identifier" Type="System.String" CanBeNull="false" />
      <Column Name="Survey_PreChat" Type="System.String" CanBeNull="false" />
      <Column Name="Survey_Exit" Type="System.String" CanBeNull="false" />
      <Column Name="Survey_Operator" Type="System.String" CanBeNull="false" />
      <Column Name="Survey_Offline" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="GeneralChatInfos">
    <Type Name="GeneralChatInfo">
      <Column Name="StartTime" Type="System.String" CanBeNull="false" />
      <Column Name="EndTime" Type="System.String" CanBeNull="false" />
      <Column Name="Duration" Type="System.String" CanBeNull="false" />
      <Column Name="StartingPage" Type="System.String" CanBeNull="false" />
      <Column Name="Operator" Type="System.String" CanBeNull="false" />
      <Column Name="Browser" Type="System.String" CanBeNull="false" />
      <Column Name="OS" Type="System.String" CanBeNull="false" />
      <Column Name="IP" Type="System.String" CanBeNull="false" />
      <Column Name="Referrer" Type="System.String" CanBeNull="false" />
      <Column Name="ChatIndicator" Type="System.String" CanBeNull="false" />
      <Column Name="RealTimeSessionID" Type="System.String" CanBeNull="false" />
      <Column Name="Country" Type="System.String" CanBeNull="false" />
      <Column Name="City" Type="System.String" CanBeNull="false" />
      <Column Name="Org" Type="System.String" CanBeNull="false" />
      <Column Name="Region" Type="System.String" CanBeNull="false" />
      <Column Name="Timezone" Type="System.String" CanBeNull="false" />
      <Column Name="ISP" Type="System.String" CanBeNull="false" />
      <Column Name="WorldRegion" Type="System.String" CanBeNull="false" />
      <Column Name="HostAddr" Type="System.String" CanBeNull="false" />
      <Column Name="PostalCode" Type="System.String" CanBeNull="false" />
      <Column Name="ConnectionType" Type="System.String" CanBeNull="false" />
      <Column Member="Country1" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="ChatTranscripts">
    <Type Name="ChatTranscript">
      <Column Name="Timestamp" Type="System.String" CanBeNull="false" />
      <Column Name="Name" Type="System.String" CanBeNull="false" />
      <Column Name="Text" Type="System.String" CanBeNull="false" />
      <Column Name="RealTimeSessionID" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="Navigations">
    <Type Name="Navigation">
      <Column Name="SeqNo" Type="System.String" CanBeNull="false" />
      <Column Name="URL" Type="System.String" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.String" CanBeNull="false" />
      <Column Name="RealTimeSessionID" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="PreChatSurveys">
    <Type Name="PreChatSurvey">
      <Column Name="IdentifierName" Type="System.String" CanBeNull="false" />
      <Column Name="Email" Type="System.String" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" CanBeNull="false" />
      <Column Name="CompanyName" Type="System.String" CanBeNull="false" />
      <Column Name="From" Type="System.String" CanBeNull="false" />
      <Column Name="RealTimeSessionID" Type="System.String" CanBeNull="false" />
      <Column Member="Country" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="" Member="CustomVariables">
    <Type Name="CustomVariables">
      <Column Name="Skill" Type="System.String" CanBeNull="false" />
      <Column Name="Abandon" Type="System.String" CanBeNull="false" />
      <Column Name="VisitorActive" Type="System.String" CanBeNull="false" />
      <Column Name="lpTagVer" Type="System.String" CanBeNull="false" />
      <Column Name="campaign_medium" Type="System.String" CanBeNull="false" />
      <Column Name="campaign_source" Type="System.String" CanBeNull="false" />
      <Column Name="RealTimeSessionID" Type="System.String" CanBeNull="false" />
    </Type>
  </Table>
</Database>