//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iABLE_Club_Console
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyAdvantechGlobalEntities : DbContext
    {
        public MyAdvantechGlobalEntities()
            : base("name=MyAdvantechGlobalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RewardRecord> RewardRecord { get; set; }
        public virtual DbSet<RewardItem> RewardItem { get; set; }
        public virtual DbSet<RewardUserLog> RewardUserLog { get; set; }
    }
}
