//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iABLE_Club_Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardRecord
    {
        public int RecordID { get; set; }
        public string StoreID { get; set; }
        public string UserID { get; set; }
        public Nullable<int> RewardID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<int> RecordType { get; set; }
        public string OrderNo { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Point { get; set; }
        public Nullable<decimal> TotalPoint { get; set; }
        public string SalesEmail { get; set; }
        public string Receiver1 { get; set; }
        public string EmailAddress1 { get; set; }
        public string CompanyName1 { get; set; }
        public string Zip1 { get; set; }
        public string Address1 { get; set; }
        public string Mobile1 { get; set; }
        public string Tel1 { get; set; }
        public string Receiver2 { get; set; }
        public string EmailAddress2 { get; set; }
        public string CompanyName2 { get; set; }
        public string Zip2 { get; set; }
        public string Address2 { get; set; }
        public string Mobile2 { get; set; }
        public string Tel2 { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> ShippingTime { get; set; }
        public Nullable<int> SendMailStatus_Internal { get; set; }
        public Nullable<int> SendMailStatus_Corporate { get; set; }
        public Nullable<int> SendMailStatus_Sales { get; set; }
    }
}
