//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iABLE_Club_Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardItem
    {
        public int RewardID { get; set; }
        public Nullable<int> ActivityID { get; set; }
        public string StoreID { get; set; }
        public string Name { get; set; }
        public string DescriptionShort { get; set; }
        public string DescriptionLong { get; set; }
        public string PartNo { get; set; }
        public Nullable<decimal> Point { get; set; }
        public string ImageFile { get; set; }
        public string ExternalURL { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<System.DateTime> SendMailDate { get; set; }
        public Nullable<int> StockQty { get; set; }
        public Nullable<int> Sequnece { get; set; }
        public Nullable<bool> PublishStatus { get; set; }
        public string Currecny { get; set; }
        public Nullable<decimal> Money { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
