//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iABLE_Club_Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class RewardUserLog
    {
        public int LogID { get; set; }
        public string StoreID { get; set; }
        public string UserID { get; set; }
        public string LogType { get; set; }
        public string URL { get; set; }
        public string Message { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
