//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BBeStoreSyncProgram.BBorderAPI {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BBorderAPISoap", Namespace="http://tempuri.org/")]
    public partial class BBorderAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBBorderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateSAPOrderFromBBeStoreOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetERPIDbyEmailOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutoMaticallyTransfereStoreOrderToSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback SynceStoreOrderToSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetContactPersonOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BBorderAPI() {
            this.Url = global::BBeStoreSyncProgram.Properties.Settings.Default.BBeStoreSyncProgram_BBorderAPI_BBorderAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBBorderCompletedEventHandler GetBBorderCompleted;
        
        /// <remarks/>
        public event CreateSAPOrderFromBBeStoreCompletedEventHandler CreateSAPOrderFromBBeStoreCompleted;
        
        /// <remarks/>
        public event ProcessCompletedEventHandler ProcessCompleted;
        
        /// <remarks/>
        public event GetERPIDbyEmailCompletedEventHandler GetERPIDbyEmailCompleted;
        
        /// <remarks/>
        public event AutoMaticallyTransfereStoreOrderToSAPCompletedEventHandler AutoMaticallyTransfereStoreOrderToSAPCompleted;
        
        /// <remarks/>
        public event SynceStoreOrderToSAPCompletedEventHandler SynceStoreOrderToSAPCompleted;
        
        /// <remarks/>
        public event GetContactPersonCompletedEventHandler GetContactPersonCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBBorder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetBBorder(string Email, string OrderNo, string OrderStatus) {
            this.Invoke("GetBBorder", new object[] {
                        Email,
                        OrderNo,
                        OrderStatus});
        }
        
        /// <remarks/>
        public void GetBBorderAsync(string Email, string OrderNo, string OrderStatus) {
            this.GetBBorderAsync(Email, OrderNo, OrderStatus, null);
        }
        
        /// <remarks/>
        public void GetBBorderAsync(string Email, string OrderNo, string OrderStatus, object userState) {
            if ((this.GetBBorderOperationCompleted == null)) {
                this.GetBBorderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBBorderOperationCompleted);
            }
            this.InvokeAsync("GetBBorder", new object[] {
                        Email,
                        OrderNo,
                        OrderStatus}, this.GetBBorderOperationCompleted, userState);
        }
        
        private void OnGetBBorderOperationCompleted(object arg) {
            if ((this.GetBBorderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBBorderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CreateSAPOrderFromBBeStore", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateSAPOrderFromBBeStore(string OrderNo) {
            this.Invoke("CreateSAPOrderFromBBeStore", new object[] {
                        OrderNo});
        }
        
        /// <remarks/>
        public void CreateSAPOrderFromBBeStoreAsync(string OrderNo) {
            this.CreateSAPOrderFromBBeStoreAsync(OrderNo, null);
        }
        
        /// <remarks/>
        public void CreateSAPOrderFromBBeStoreAsync(string OrderNo, object userState) {
            if ((this.CreateSAPOrderFromBBeStoreOperationCompleted == null)) {
                this.CreateSAPOrderFromBBeStoreOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateSAPOrderFromBBeStoreOperationCompleted);
            }
            this.InvokeAsync("CreateSAPOrderFromBBeStore", new object[] {
                        OrderNo}, this.CreateSAPOrderFromBBeStoreOperationCompleted, userState);
        }
        
        private void OnCreateSAPOrderFromBBeStoreOperationCompleted(object arg) {
            if ((this.CreateSAPOrderFromBBeStoreCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateSAPOrderFromBBeStoreCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Process", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public WebServiceResult Process(string OrderNo) {
            object[] results = this.Invoke("Process", new object[] {
                        OrderNo});
            return ((WebServiceResult)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessAsync(string OrderNo) {
            this.ProcessAsync(OrderNo, null);
        }
        
        /// <remarks/>
        public void ProcessAsync(string OrderNo, object userState) {
            if ((this.ProcessOperationCompleted == null)) {
                this.ProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessOperationCompleted);
            }
            this.InvokeAsync("Process", new object[] {
                        OrderNo}, this.ProcessOperationCompleted, userState);
        }
        
        private void OnProcessOperationCompleted(object arg) {
            if ((this.ProcessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessCompleted(this, new ProcessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetERPIDbyEmail", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BBCustomer GetERPIDbyEmail(string userID) {
            object[] results = this.Invoke("GetERPIDbyEmail", new object[] {
                        userID});
            return ((BBCustomer)(results[0]));
        }
        
        /// <remarks/>
        public void GetERPIDbyEmailAsync(string userID) {
            this.GetERPIDbyEmailAsync(userID, null);
        }
        
        /// <remarks/>
        public void GetERPIDbyEmailAsync(string userID, object userState) {
            if ((this.GetERPIDbyEmailOperationCompleted == null)) {
                this.GetERPIDbyEmailOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetERPIDbyEmailOperationCompleted);
            }
            this.InvokeAsync("GetERPIDbyEmail", new object[] {
                        userID}, this.GetERPIDbyEmailOperationCompleted, userState);
        }
        
        private void OnGetERPIDbyEmailOperationCompleted(object arg) {
            if ((this.GetERPIDbyEmailCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetERPIDbyEmailCompleted(this, new GetERPIDbyEmailCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AutoMaticallyTransfereStoreOrderToSAP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AutoMaticallyTransfereStoreOrderToSAP() {
            this.Invoke("AutoMaticallyTransfereStoreOrderToSAP", new object[0]);
        }
        
        /// <remarks/>
        public void AutoMaticallyTransfereStoreOrderToSAPAsync() {
            this.AutoMaticallyTransfereStoreOrderToSAPAsync(null);
        }
        
        /// <remarks/>
        public void AutoMaticallyTransfereStoreOrderToSAPAsync(object userState) {
            if ((this.AutoMaticallyTransfereStoreOrderToSAPOperationCompleted == null)) {
                this.AutoMaticallyTransfereStoreOrderToSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutoMaticallyTransfereStoreOrderToSAPOperationCompleted);
            }
            this.InvokeAsync("AutoMaticallyTransfereStoreOrderToSAP", new object[0], this.AutoMaticallyTransfereStoreOrderToSAPOperationCompleted, userState);
        }
        
        private void OnAutoMaticallyTransfereStoreOrderToSAPOperationCompleted(object arg) {
            if ((this.AutoMaticallyTransfereStoreOrderToSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutoMaticallyTransfereStoreOrderToSAPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynceStoreOrderToSAP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SynceStoreOrderToSAP(string OrderNo) {
            this.Invoke("SynceStoreOrderToSAP", new object[] {
                        OrderNo});
        }
        
        /// <remarks/>
        public void SynceStoreOrderToSAPAsync(string OrderNo) {
            this.SynceStoreOrderToSAPAsync(OrderNo, null);
        }
        
        /// <remarks/>
        public void SynceStoreOrderToSAPAsync(string OrderNo, object userState) {
            if ((this.SynceStoreOrderToSAPOperationCompleted == null)) {
                this.SynceStoreOrderToSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynceStoreOrderToSAPOperationCompleted);
            }
            this.InvokeAsync("SynceStoreOrderToSAP", new object[] {
                        OrderNo}, this.SynceStoreOrderToSAPOperationCompleted, userState);
        }
        
        private void OnSynceStoreOrderToSAPOperationCompleted(object arg) {
            if ((this.SynceStoreOrderToSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynceStoreOrderToSAPCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetContactPerson", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GetContactPerson(string Email, string ERPID) {
            this.Invoke("GetContactPerson", new object[] {
                        Email,
                        ERPID});
        }
        
        /// <remarks/>
        public void GetContactPersonAsync(string Email, string ERPID) {
            this.GetContactPersonAsync(Email, ERPID, null);
        }
        
        /// <remarks/>
        public void GetContactPersonAsync(string Email, string ERPID, object userState) {
            if ((this.GetContactPersonOperationCompleted == null)) {
                this.GetContactPersonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetContactPersonOperationCompleted);
            }
            this.InvokeAsync("GetContactPerson", new object[] {
                        Email,
                        ERPID}, this.GetContactPersonOperationCompleted, userState);
        }
        
        private void OnGetContactPersonOperationCompleted(object arg) {
            if ((this.GetContactPersonCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetContactPersonCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WebServiceResult {
        
        private string orderNoField;
        
        private bool resultField;
        
        private string messageField;
        
        /// <remarks/>
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
            }
        }
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2117.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BBCustomer {
        
        private string customerIDField;
        
        private string userIDField;
        
        private string netTermField;
        
        /// <remarks/>
        public string CustomerID {
            get {
                return this.customerIDField;
            }
            set {
                this.customerIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string NetTerm {
            get {
                return this.netTermField;
            }
            set {
                this.netTermField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetBBorderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void CreateSAPOrderFromBBeStoreCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void ProcessCompletedEventHandler(object sender, ProcessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public WebServiceResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((WebServiceResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetERPIDbyEmailCompletedEventHandler(object sender, GetERPIDbyEmailCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetERPIDbyEmailCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetERPIDbyEmailCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public BBCustomer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((BBCustomer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void AutoMaticallyTransfereStoreOrderToSAPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void SynceStoreOrderToSAPCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2053.0")]
    public delegate void GetContactPersonCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591